apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
  # annotations:
  #   notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "gitops"
  #   notifications.argoproj.io/subscribe.on-update-started.slack: "gitops"
  #   notifications.argoproj.io/subscribe.on-update-failed.slack: "gitops"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
