apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
---            
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-1
  labels:
    app: hello-nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx-1
  template:
    metadata:
      labels:
        app: hello-nginx-1
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
